# Generated by Django 3.2.6 on 2021-09-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.CharField(max_length=32)),
                ('postURL', models.CharField(max_length=500)),
                ('stock', models.CharField(max_length=32)),
                ('ups', models.IntegerField(blank=True)),
                ('downs', models.IntegerField(blank=True)),
                ('numComments', models.IntegerField(blank=True)),
            ],
        ),
    ]
